version: '3.9'
services:
    music:
        build: 
            context: .
            dockerfile: music/Dockerfile 
        restart: always

    manage:
        build:
            context: .
            dockerfile: manage/Dockerfile
        restart: always
        env_file:
            - manage.env
