version: '3.9'
services:
    music:
        build: 
            context: .
            dockerfile: music/Dockerfile 

    manage:
        build:
            context: .
            dockerfile: manage/Dockerfile

