version: '3'

services:
  music:
    build: 
      context: .
      dockerfile: music/Dockerfile 

  manage:
    build:
      context: .
      dockerfile: manage/Dockerfile
    env_file:
      - manage.env